// AUTO-GENERATED by scripts/generate-applyhome-presales.py — 편집 금지.
// 출처: 한국부동산원 청약홈 APT 분양정보(공공데이터, 2025-11-28). 일정·세대·규제플래그=공식값.
// 분양가·평형별은 미포함(주택형별 자료 필요) · metrics/통근은 placeholder. 안양/광명권만.
import type { PresaleHome } from "@/domain/types";
import { regulatoryConditions } from "@/domain/eligibility";

const COMMUTE = {"gwangmyeong": {"gangnam": 35, "pangyo": 50, "yeouido": 30, "gwanghwamun": 35, "jamsil": 45, "magok": 30, "guro-gasan": 15}, "pyeongchon": {"gangnam": 45, "pangyo": 30, "yeouido": 45, "gwanghwamun": 50, "jamsil": 50, "magok": 55, "guro-gasan": 25}, "anyang": {"gangnam": 50, "pangyo": 40, "yeouido": 40, "gwanghwamun": 45, "jamsil": 55, "magok": 50, "guro-gasan": 20}, "gunpo": {"gangnam": 50, "pangyo": 40, "yeouido": 45, "gwanghwamun": 55, "jamsil": 55, "magok": 55, "guro-gasan": 30}, "uiwang": {"gangnam": 45, "pangyo": 30, "yeouido": 50, "gwanghwamun": 55, "jamsil": 50, "magok": 60, "guro-gasan": 30}} as const;

export const APPLYHOME_REAL_PRESALES: PresaleHome[] = [
  {
    kind: "presale",
    id: "applyhome-2025000549",
    name: "의왕시청역 SK VIEW IPARK",
    regionId: "uiwang",
    price: {}, // 분양가·평형별은 청약홈 주택형별 자료 필요(공고 확인)
    sizesPyeong: [],
    moveInYear: 2030,
    households: 958,
    commuteMinutes: COMMUTE.uiwang, // mock 추정
    metrics: { education: 68, infrastructure: 72, environment: 70, futurePotential: 72 }, // placeholder seed(실측 아님)
    housingType: "apartment",
    subscription: {
      type: "general",
      scheduleNote: "공고 2025-11-21 · 특공 2025-12-01 · 1순위 2025-12-02 · 발표 2025-12-10",
      conditions: { ...regulatoryConditions("speculation_overheated", { overcrowdedZone: true }), note: "청약홈 공고 기준(일정·규제) · 실거주/거주기간은 공고 확인" },
    },
  },
  {
    kind: "presale",
    id: "applyhome-2025000423",
    name: "안양자이 헤리티온",
    regionId: "anyang",
    price: {}, // 분양가·평형별은 청약홈 주택형별 자료 필요(공고 확인)
    sizesPyeong: [],
    moveInYear: 2029,
    households: 639,
    commuteMinutes: COMMUTE.anyang, // mock 추정
    metrics: { education: 68, infrastructure: 72, environment: 70, futurePotential: 72 }, // placeholder seed(실측 아님)
    housingType: "apartment",
    subscription: {
      type: "general",
      scheduleNote: "공고 2025-11-21 · 특공 2025-12-02 · 1순위 2025-12-03 · 발표 2025-12-10",
      conditions: { ...regulatoryConditions("none", { overcrowdedZone: true }), note: "청약홈 공고 기준(일정·규제) · 실거주/거주기간은 공고 확인" },
    },
  },
  {
    kind: "presale",
    id: "applyhome-2025000556",
    name: "힐스테이트 광명 11",
    regionId: "gwangmyeong",
    price: {}, // 분양가·평형별은 청약홈 주택형별 자료 필요(공고 확인)
    sizesPyeong: [],
    moveInYear: 2029,
    households: 652,
    commuteMinutes: COMMUTE.gwangmyeong, // mock 추정
    metrics: { education: 68, infrastructure: 72, environment: 70, futurePotential: 72 }, // placeholder seed(실측 아님)
    housingType: "apartment",
    subscription: {
      type: "general",
      scheduleNote: "공고 2025-11-07 · 특공 2025-11-17 · 1순위 2025-11-18 · 발표 2025-11-26",
      conditions: { ...regulatoryConditions("none", { overcrowdedZone: true }), note: "청약홈 공고 기준(일정·규제) · 실거주/거주기간은 공고 확인" },
    },
  },
  {
    kind: "presale",
    id: "applyhome-2025000472",
    name: "만안역 중앙하이츠 포레",
    regionId: "anyang",
    price: {}, // 분양가·평형별은 청약홈 주택형별 자료 필요(공고 확인)
    sizesPyeong: [],
    moveInYear: 2028,
    households: 47,
    commuteMinutes: COMMUTE.anyang, // mock 추정
    metrics: { education: 68, infrastructure: 72, environment: 70, futurePotential: 72 }, // placeholder seed(실측 아님)
    housingType: "apartment",
    subscription: {
      type: "general",
      scheduleNote: "공고 2025-10-24 · 특공 2025-11-03 · 1순위 2025-11-04 · 발표 2025-11-11",
      conditions: { ...regulatoryConditions("none", { overcrowdedZone: true }), note: "청약홈 공고 기준(일정·규제) · 실거주/거주기간은 공고 확인" },
    },
  },
  {
    kind: "presale",
    id: "applyhome-2025000429",
    name: "철산역자이",
    regionId: "gwangmyeong",
    price: {}, // 분양가·평형별은 청약홈 주택형별 자료 필요(공고 확인)
    sizesPyeong: [],
    moveInYear: 2029,
    households: 650,
    commuteMinutes: COMMUTE.gwangmyeong, // mock 추정
    metrics: { education: 68, infrastructure: 72, environment: 70, futurePotential: 72 }, // placeholder seed(실측 아님)
    housingType: "apartment",
    subscription: {
      type: "general",
      scheduleNote: "공고 2025-09-19 · 특공 2025-09-29 · 1순위 2025-09-30 · 발표 2025-10-15",
      conditions: { ...regulatoryConditions("none", { overcrowdedZone: true }), note: "청약홈 공고 기준(일정·규제) · 실거주/거주기간은 공고 확인" },
    },
  },
  {
    kind: "presale",
    id: "applyhome-2025000287",
    name: "대야미역 금강펜테리움 레이크포레(B1BL)",
    regionId: "gunpo",
    price: {}, // 분양가·평형별은 청약홈 주택형별 자료 필요(공고 확인)
    sizesPyeong: [],
    moveInYear: 2028,
    households: 452,
    commuteMinutes: COMMUTE.gunpo, // mock 추정
    metrics: { education: 68, infrastructure: 72, environment: 70, futurePotential: 72 }, // placeholder seed(실측 아님)
    housingType: "apartment",
    subscription: {
      type: "general",
      scheduleNote: "공고 2025-07-18 · 특공 2025-07-28 · 1순위 2025-07-29 · 발표 2025-08-05",
      conditions: { ...regulatoryConditions("none", { overcrowdedZone: true }), note: "청약홈 공고 기준(일정·규제) · 실거주/거주기간은 공고 확인" },
    },
  },
  {
    kind: "presale",
    id: "applyhome-2025000246",
    name: "호현 센트럴 아이파크",
    regionId: "anyang",
    price: {}, // 분양가·평형별은 청약홈 주택형별 자료 필요(공고 확인)
    sizesPyeong: [],
    moveInYear: 2028,
    households: 144,
    commuteMinutes: COMMUTE.anyang, // mock 추정
    metrics: { education: 68, infrastructure: 72, environment: 70, futurePotential: 72 }, // placeholder seed(실측 아님)
    housingType: "apartment",
    subscription: {
      type: "general",
      scheduleNote: "공고 2025-06-20 · 특공 2025-06-30 · 1순위 2025-07-01 · 발표 2025-07-08",
      conditions: { ...regulatoryConditions("none", { overcrowdedZone: true }), note: "청약홈 공고 기준(일정·규제) · 실거주/거주기간은 공고 확인" },
    },
  },
  {
    kind: "presale",
    id: "applyhome-2025820006",
    name: "의왕월암 A-3블록 신혼희망타운(공공분양) 추가입주자 모집",
    regionId: "uiwang",
    price: {}, // 분양가·평형별은 청약홈 주택형별 자료 필요(공고 확인)
    sizesPyeong: [],
    moveInYear: 2028,
    households: 77,
    commuteMinutes: COMMUTE.uiwang, // mock 추정
    metrics: { education: 68, infrastructure: 72, environment: 70, futurePotential: 72 }, // placeholder seed(실측 아님)
    housingType: "apartment",
    subscription: {
      type: "general",
      scheduleNote: "공고 2025-05-22 · 1순위 2025-06-04 · 발표 2025-06-13",
      conditions: { ...regulatoryConditions("none", { overcrowdedZone: true }), note: "청약홈 공고 기준(일정·규제) · 실거주/거주기간은 공고 확인" },
    },
  },
  {
    kind: "presale",
    id: "applyhome-2025820004",
    name: "의왕월암 A-1블록 신혼희망타운(공공분양) 추가입주자 모집",
    regionId: "uiwang",
    price: {}, // 분양가·평형별은 청약홈 주택형별 자료 필요(공고 확인)
    sizesPyeong: [],
    moveInYear: 2027,
    households: 111,
    commuteMinutes: COMMUTE.uiwang, // mock 추정
    metrics: { education: 68, infrastructure: 72, environment: 70, futurePotential: 72 }, // placeholder seed(실측 아님)
    housingType: "apartment",
    subscription: {
      type: "general",
      scheduleNote: "공고 2025-05-22 · 1순위 2025-06-04 · 발표 2025-06-13",
      conditions: { ...regulatoryConditions("none", { overcrowdedZone: true }), note: "청약홈 공고 기준(일정·규제) · 실거주/거주기간은 공고 확인" },
    },
  },
  {
    kind: "presale",
    id: "applyhome-2025000053",
    name: "더샵 금정위버시티(조합원 취소분)",
    regionId: "gunpo",
    price: {}, // 분양가·평형별은 청약홈 주택형별 자료 필요(공고 확인)
    sizesPyeong: [],
    moveInYear: 2027,
    households: 30,
    commuteMinutes: COMMUTE.gunpo, // mock 추정
    metrics: { education: 68, infrastructure: 72, environment: 70, futurePotential: 72 }, // placeholder seed(실측 아님)
    housingType: "apartment",
    subscription: {
      type: "general",
      scheduleNote: "공고 2025-05-09 · 1순위 2025-05-19 · 발표 2025-05-26",
      conditions: { ...regulatoryConditions("none", { overcrowdedZone: true }), note: "청약홈 공고 기준(일정·규제) · 실거주/거주기간은 공고 확인" },
    },
  },
  {
    kind: "presale",
    id: "applyhome-2025000135",
    name: "청계 노르웨이숲",
    regionId: "uiwang",
    price: {}, // 분양가·평형별은 청약홈 주택형별 자료 필요(공고 확인)
    sizesPyeong: [],
    moveInYear: 2028,
    households: 97,
    commuteMinutes: COMMUTE.uiwang, // mock 추정
    metrics: { education: 68, infrastructure: 72, environment: 70, futurePotential: 72 }, // placeholder seed(실측 아님)
    housingType: "apartment",
    subscription: {
      type: "general",
      scheduleNote: "공고 2025-04-18 · 특공 2025-04-28 · 1순위 2025-04-29 · 발표 2025-05-12",
      conditions: { ...regulatoryConditions("none", { overcrowdedZone: true }), note: "청약홈 공고 기준(일정·규제) · 실거주/거주기간은 공고 확인" },
    },
  },
  {
    kind: "presale",
    id: "applyhome-2025000129",
    name: "제일풍경채 의왕고천(본청약)",
    regionId: "uiwang",
    price: {}, // 분양가·평형별은 청약홈 주택형별 자료 필요(공고 확인)
    sizesPyeong: [],
    moveInYear: 2026,
    households: 466,
    commuteMinutes: COMMUTE.uiwang, // mock 추정
    metrics: { education: 68, infrastructure: 72, environment: 70, futurePotential: 72 }, // placeholder seed(실측 아님)
    housingType: "apartment",
    subscription: {
      type: "general",
      scheduleNote: "공고 2025-04-18 · 특공 2025-04-28 · 1순위 2025-04-29 · 발표 2025-05-09",
      conditions: { ...regulatoryConditions("none", { overcrowdedZone: true }), note: "청약홈 공고 기준(일정·규제) · 실거주/거주기간은 공고 확인" },
    },
  },
  {
    kind: "presale",
    id: "applyhome-2024820018",
    name: "의왕청계2 A1블록 신혼희망타운(공공분양)(본청약)",
    regionId: "uiwang",
    price: {}, // 분양가·평형별은 청약홈 주택형별 자료 필요(공고 확인)
    sizesPyeong: [],
    moveInYear: 2028,
    households: 320,
    commuteMinutes: COMMUTE.uiwang, // mock 추정
    metrics: { education: 68, infrastructure: 72, environment: 70, futurePotential: 72 }, // placeholder seed(실측 아님)
    housingType: "apartment",
    subscription: {
      type: "general",
      scheduleNote: "공고 2024-12-30 · 1순위 2025-01-15 · 발표 2025-01-24",
      conditions: { ...regulatoryConditions("none", { overcrowdedZone: true }), note: "청약홈 공고 기준(일정·규제) · 실거주/거주기간은 공고 확인" },
    },
  },
  {
    kind: "presale",
    id: "applyhome-2024000706",
    name: "의왕 월암지구 대방 디에트르 레이크파크",
    regionId: "uiwang",
    price: {}, // 분양가·평형별은 청약홈 주택형별 자료 필요(공고 확인)
    sizesPyeong: [],
    moveInYear: 2027,
    households: 702,
    commuteMinutes: COMMUTE.uiwang, // mock 추정
    metrics: { education: 68, infrastructure: 72, environment: 70, futurePotential: 72 }, // placeholder seed(실측 아님)
    housingType: "apartment",
    subscription: {
      type: "general",
      scheduleNote: "공고 2024-12-20 · 특공 2024-12-30 · 1순위 2024-12-31 · 발표 2025-01-08",
      conditions: { ...regulatoryConditions("none", { overcrowdedZone: true }), note: "청약홈 공고 기준(일정·규제) · 실거주/거주기간은 공고 확인" },
    },
  },
  {
    kind: "presale",
    id: "applyhome-2024000668",
    name: "평촌자이 퍼스니티",
    regionId: "pyeongchon",
    price: {}, // 분양가·평형별은 청약홈 주택형별 자료 필요(공고 확인)
    sizesPyeong: [],
    moveInYear: 2027,
    households: 570,
    commuteMinutes: COMMUTE.pyeongchon, // mock 추정
    metrics: { education: 68, infrastructure: 72, environment: 70, futurePotential: 72 }, // placeholder seed(실측 아님)
    housingType: "apartment",
    subscription: {
      type: "general",
      scheduleNote: "공고 2024-11-14 · 특공 2024-11-25 · 1순위 2024-11-26 · 발표 2024-12-04",
      conditions: { ...regulatoryConditions("none", { overcrowdedZone: true }), note: "청약홈 공고 기준(일정·규제) · 실거주/거주기간은 공고 확인" },
    },
  },
  {
    kind: "presale",
    id: "applyhome-2024820015",
    name: "의왕월암 A-3블록 신혼희망타운(공공분양)(본청약)",
    regionId: "uiwang",
    price: {}, // 분양가·평형별은 청약홈 주택형별 자료 필요(공고 확인)
    sizesPyeong: [],
    moveInYear: 2028,
    households: 424,
    commuteMinutes: COMMUTE.uiwang, // mock 추정
    metrics: { education: 68, infrastructure: 72, environment: 70, futurePotential: 72 }, // placeholder seed(실측 아님)
    housingType: "apartment",
    subscription: {
      type: "general",
      scheduleNote: "공고 2024-11-08 · 1순위 2024-11-18 · 발표 2024-11-29",
      conditions: { ...regulatoryConditions("none", { overcrowdedZone: true }), note: "청약홈 공고 기준(일정·규제) · 실거주/거주기간은 공고 확인" },
    },
  },
  {
    kind: "presale",
    id: "applyhome-2024820014",
    name: "의왕월암 A-1블록 신혼희망타운(공공분양)(본청약)",
    regionId: "uiwang",
    price: {}, // 분양가·평형별은 청약홈 주택형별 자료 필요(공고 확인)
    sizesPyeong: [],
    moveInYear: 2027,
    households: 446,
    commuteMinutes: COMMUTE.uiwang, // mock 추정
    metrics: { education: 68, infrastructure: 72, environment: 70, futurePotential: 72 }, // placeholder seed(실측 아님)
    housingType: "apartment",
    subscription: {
      type: "general",
      scheduleNote: "공고 2024-11-08 · 1순위 2024-11-18 · 발표 2024-11-29",
      conditions: { ...regulatoryConditions("none", { overcrowdedZone: true }), note: "청약홈 공고 기준(일정·규제) · 실거주/거주기간은 공고 확인" },
    },
  },
  {
    kind: "presale",
    id: "applyhome-2024000601",
    name: "군포대야미 대방 디에트르 시그니처(B3BL)",
    regionId: "gunpo",
    price: {}, // 분양가·평형별은 청약홈 주택형별 자료 필요(공고 확인)
    sizesPyeong: [],
    moveInYear: 2027,
    households: 568,
    commuteMinutes: COMMUTE.gunpo, // mock 추정
    metrics: { education: 68, infrastructure: 72, environment: 70, futurePotential: 72 }, // placeholder seed(실측 아님)
    housingType: "apartment",
    subscription: {
      type: "general",
      scheduleNote: "공고 2024-11-08 · 특공 2024-11-18 · 1순위 2024-11-19 · 발표 2024-11-28",
      conditions: { ...regulatoryConditions("none", { overcrowdedZone: true }), note: "청약홈 공고 기준(일정·규제) · 실거주/거주기간은 공고 확인" },
    },
  },
  {
    kind: "presale",
    id: "applyhome-2024000563",
    name: "아크로 베스티뉴",
    regionId: "pyeongchon",
    price: {}, // 분양가·평형별은 청약홈 주택형별 자료 필요(공고 확인)
    sizesPyeong: [],
    moveInYear: 2025,
    households: 391,
    commuteMinutes: COMMUTE.pyeongchon, // mock 추정
    metrics: { education: 68, infrastructure: 72, environment: 70, futurePotential: 72 }, // placeholder seed(실측 아님)
    housingType: "apartment",
    subscription: {
      type: "general",
      scheduleNote: "공고 2024-11-07 · 특공 2024-11-18 · 1순위 2024-11-19 · 발표 2024-11-27",
      conditions: { ...regulatoryConditions("none", { overcrowdedZone: true }), note: "청약홈 공고 기준(일정·규제) · 실거주/거주기간은 공고 확인" },
    },
  },
  {
    kind: "presale",
    id: "applyhome-2024000602",
    name: "광명 유승한내들 라포레",
    regionId: "gwangmyeong",
    price: {}, // 분양가·평형별은 청약홈 주택형별 자료 필요(공고 확인)
    sizesPyeong: [],
    moveInYear: 2027,
    households: 444,
    commuteMinutes: COMMUTE.gwangmyeong, // mock 추정
    metrics: { education: 68, infrastructure: 72, environment: 70, futurePotential: 72 }, // placeholder seed(실측 아님)
    housingType: "apartment",
    subscription: {
      type: "general",
      scheduleNote: "공고 2024-10-31 · 특공 2024-11-11 · 1순위 2024-11-12 · 발표 2024-11-19",
      conditions: { ...regulatoryConditions("none", { overcrowdedZone: true }), note: "청약홈 공고 기준(일정·규제) · 실거주/거주기간은 공고 확인" },
    },
  },
  {
    kind: "presale",
    id: "applyhome-2024000407",
    name: "의왕고천지구 대방 디에트르 센트럴(B1BL)",
    regionId: "uiwang",
    price: {}, // 분양가·평형별은 청약홈 주택형별 자료 필요(공고 확인)
    sizesPyeong: [],
    moveInYear: 2025,
    households: 492,
    commuteMinutes: COMMUTE.uiwang, // mock 추정
    metrics: { education: 68, infrastructure: 72, environment: 70, futurePotential: 72 }, // placeholder seed(실측 아님)
    housingType: "apartment",
    subscription: {
      type: "general",
      scheduleNote: "공고 2024-10-24 · 특공 2024-11-04 · 1순위 2024-11-05 · 발표 2024-11-14",
      conditions: { ...regulatoryConditions("none", { overcrowdedZone: true }), note: "청약홈 공고 기준(일정·규제) · 실거주/거주기간은 공고 확인" },
    },
  },
  {
    kind: "presale",
    id: "applyhome-2024000168",
    name: "금정역 푸르지오 그랑블",
    regionId: "gunpo",
    price: {}, // 분양가·평형별은 청약홈 주택형별 자료 필요(공고 확인)
    sizesPyeong: [],
    moveInYear: 2028,
    households: 1072,
    commuteMinutes: COMMUTE.gunpo, // mock 추정
    metrics: { education: 68, infrastructure: 72, environment: 70, futurePotential: 72 }, // placeholder seed(실측 아님)
    housingType: "apartment",
    subscription: {
      type: "general",
      scheduleNote: "공고 2024-06-07 · 특공 2024-06-17 · 1순위 2024-06-18 · 발표 2024-06-26",
      conditions: { ...regulatoryConditions("none", { overcrowdedZone: true }), note: "청약홈 공고 기준(일정·규제) · 실거주/거주기간은 공고 확인" },
    },
  },
  {
    kind: "presale",
    id: "applyhome-2024820005",
    name: "의왕초평 A-3블록 신혼희망타운(공공분양) 잔여세대 추가입주자모집공고",
    regionId: "uiwang",
    price: {}, // 분양가·평형별은 청약홈 주택형별 자료 필요(공고 확인)
    sizesPyeong: [],
    moveInYear: 2024,
    households: 23,
    commuteMinutes: COMMUTE.uiwang, // mock 추정
    metrics: { education: 68, infrastructure: 72, environment: 70, futurePotential: 72 }, // placeholder seed(실측 아님)
    housingType: "apartment",
    subscription: {
      type: "general",
      scheduleNote: "공고 2024-05-13 · 1순위 2024-05-23 · 발표 2024-05-27",
      conditions: { ...regulatoryConditions("none", { overcrowdedZone: true }), note: "청약홈 공고 기준(일정·규제) · 실거주/거주기간은 공고 확인" },
    },
  },
  {
    kind: "presale",
    id: "applyhome-2024000164",
    name: "광명 롯데캐슬 시그니처",
    regionId: "gwangmyeong",
    price: {}, // 분양가·평형별은 청약홈 주택형별 자료 필요(공고 확인)
    sizesPyeong: [],
    moveInYear: 2027,
    households: 533,
    commuteMinutes: COMMUTE.gwangmyeong, // mock 추정
    metrics: { education: 68, infrastructure: 72, environment: 70, futurePotential: 72 }, // placeholder seed(실측 아님)
    housingType: "apartment",
    subscription: {
      type: "general",
      scheduleNote: "공고 2024-04-25 · 특공 2024-05-07 · 1순위 2024-05-08 · 발표 2024-05-16",
      conditions: { ...regulatoryConditions("none", { overcrowdedZone: true }), note: "청약홈 공고 기준(일정·규제) · 실거주/거주기간은 공고 확인" },
    },
  },
  {
    kind: "presale",
    id: "applyhome-2024000112",
    name: "e편한세상 금정 메종카운티",
    regionId: "gunpo",
    price: {}, // 분양가·평형별은 청약홈 주택형별 자료 필요(공고 확인)
    sizesPyeong: [],
    moveInYear: 2026,
    households: 123,
    commuteMinutes: COMMUTE.gunpo, // mock 추정
    metrics: { education: 68, infrastructure: 72, environment: 70, futurePotential: 72 }, // placeholder seed(실측 아님)
    housingType: "apartment",
    subscription: {
      type: "general",
      scheduleNote: "공고 2024-04-05 · 특공 2024-04-15 · 1순위 2024-04-16 · 발표 2024-04-23",
      conditions: { ...regulatoryConditions("none", { overcrowdedZone: true }), note: "청약홈 공고 기준(일정·규제) · 실거주/거주기간은 공고 확인" },
    },
  },
  {
    kind: "presale",
    id: "applyhome-2024000081",
    name: "e편한세상 평촌 어반밸리",
    regionId: "pyeongchon",
    price: {}, // 분양가·평형별은 청약홈 주택형별 자료 필요(공고 확인)
    sizesPyeong: [],
    moveInYear: 2026,
    households: 458,
    commuteMinutes: COMMUTE.pyeongchon, // mock 추정
    metrics: { education: 68, infrastructure: 72, environment: 70, futurePotential: 72 }, // placeholder seed(실측 아님)
    housingType: "apartment",
    subscription: {
      type: "general",
      scheduleNote: "공고 2024-02-29 · 특공 2024-03-13 · 1순위 2024-03-14 · 발표 2024-03-21",
      conditions: { ...regulatoryConditions("none", { overcrowdedZone: true }), note: "청약홈 공고 기준(일정·규제) · 실거주/거주기간은 공고 확인" },
    },
  },
  {
    kind: "presale",
    id: "applyhome-2023000708",
    name: "더샵 금정위버시티",
    regionId: "gunpo",
    price: {}, // 분양가·평형별은 청약홈 주택형별 자료 필요(공고 확인)
    sizesPyeong: [],
    moveInYear: 2027,
    households: 308,
    commuteMinutes: COMMUTE.gunpo, // mock 추정
    metrics: { education: 68, infrastructure: 72, environment: 70, futurePotential: 72 }, // placeholder seed(실측 아님)
    housingType: "apartment",
    subscription: {
      type: "general",
      scheduleNote: "공고 2024-02-23 · 특공 2024-03-04 · 1순위 2024-03-05 · 발표 2024-03-13",
      conditions: { ...regulatoryConditions("none", { overcrowdedZone: true }), note: "청약홈 공고 기준(일정·규제) · 실거주/거주기간은 공고 확인" },
    },
  },
  {
    kind: "presale",
    id: "applyhome-2024820002",
    name: "의왕고천 A-2BL 신혼희망타운(공공분양) 잔여세대",
    regionId: "uiwang",
    price: {}, // 분양가·평형별은 청약홈 주택형별 자료 필요(공고 확인)
    sizesPyeong: [],
    moveInYear: 2024,
    households: 1,
    commuteMinutes: COMMUTE.uiwang, // mock 추정
    metrics: { education: 68, infrastructure: 72, environment: 70, futurePotential: 72 }, // placeholder seed(실측 아님)
    housingType: "apartment",
    subscription: {
      type: "general",
      scheduleNote: "공고 2024-02-22 · 1순위 2024-02-28 · 발표 2024-03-05",
      conditions: { ...regulatoryConditions("none", { overcrowdedZone: true }), note: "청약홈 공고 기준(일정·규제) · 실거주/거주기간은 공고 확인" },
    },
  }
];
