#!/usr/bin/env python3
# 청약홈 APT 분양정보 CSV(한국부동산원, 공공데이터) → PresaleHome[] TS 생성.
# 안양/광명권(앱이 다루는 지역)만 매핑. **일정·세대·규제플래그는 공식값** 그대로.
# 규제 조건(전매·재당첨·통장)은 CSV의 규제플래그 → regulatoryConditions로 도출(런타임).
# 분양가·평형별 물량은 이 CSV에 없음(주택형별 별도) → price 비움. metrics는 지역 placeholder seed.
#
#   python3 scripts/generate-applyhome-presales.py
import csv

SRC = "src/data/real/sources/applyhome-apt-2025-11-28.csv"
OUT = "src/data/real/presales.applyhome.ts"
MIN_YEAR = "2024"

# 주소/주택명 키워드 → 앱 region.
KW = {
    "gwangmyeong": ["광명", "철산", "하안", "소하"],
    "pyeongchon": ["평촌", "비산", "관양", "호계", "인덕원"],
    "anyang": ["안양", "만안", "박달", "석수"],
    "gunpo": ["산본", "군포", "금정", "대야미"],
    "uiwang": ["의왕", "내손", "오전", "고천", "청계", "월암"],
}
# 지역 통근 placeholder(mock 추정) · metrics seed(placeholder).
COMMUTE = {
    "gwangmyeong": {"gangnam": 35, "pangyo": 50, "yeouido": 30, "gwanghwamun": 35, "jamsil": 45, "magok": 30, "guro-gasan": 15},
    "pyeongchon": {"gangnam": 45, "pangyo": 30, "yeouido": 45, "gwanghwamun": 50, "jamsil": 50, "magok": 55, "guro-gasan": 25},
    "anyang": {"gangnam": 50, "pangyo": 40, "yeouido": 40, "gwanghwamun": 45, "jamsil": 55, "magok": 50, "guro-gasan": 20},
    "gunpo": {"gangnam": 50, "pangyo": 40, "yeouido": 45, "gwanghwamun": 55, "jamsil": 55, "magok": 55, "guro-gasan": 30},
    "uiwang": {"gangnam": 45, "pangyo": 30, "yeouido": 50, "gwanghwamun": 55, "jamsil": 50, "magok": 60, "guro-gasan": 30},
}
METRICS = "{ education: 68, infrastructure: 72, environment: 70, futurePotential: 72 }"  # placeholder seed


def region(name, loc):
    s = (name or "") + (loc or "")
    for reg, kws in KW.items():
        if any(k in s for k in kws):
            return reg
    return None


def esc(s):
    return '"' + (s or "").strip().replace("\\", "").replace('"', "'") + '"'


def main():
    rows = list(csv.reader(open(SRC, encoding="utf-8")))[1:]
    entries, seen = [], set()
    for r in rows:
        if len(r) < 42:
            continue
        pblanc, name, loc, size = r[1].strip(), r[2].strip(), r[12], r[13]
        ann = (r[14] or "").strip()
        if ann[:4] < MIN_YEAR:
            continue
        reg = region(name, loc)
        if not reg:
            continue
        dev_id = f"applyhome-{pblanc}"
        if dev_id in seen:
            continue
        seen.add(dev_id)
        move_in = (r[38] or "")[:4]
        households = None
        try:
            households = int(str(size).replace(",", ""))
        except Exception:
            pass
        # 규제지역: 투기과열(39) > 조정대상(40) > 비규제.
        area = "speculation_overheated" if r[39].strip() == "Y" else "adjustment" if r[40].strip() == "Y" else "none"
        # 일정 요약(모집공고·특공·1순위·발표).
        parts = []
        if ann: parts.append(f"공고 {ann}")
        if (r[17] or "").strip(): parts.append(f"특공 {r[17].strip()}")
        if (r[19] or "").strip(): parts.append(f"1순위 {r[19].strip()}")
        if (r[31] or "").strip(): parts.append(f"발표 {r[31].strip()}")
        note = " · ".join(parts)

        e = (
            "  {\n"
            '    kind: "presale",\n'
            f"    id: {esc(dev_id)},\n"
            f"    name: {esc(name)},\n"
            f'    regionId: "{reg}",\n'
            "    price: {}, // 분양가·평형별은 청약홈 주택형별 자료 필요(공고 확인)\n"
            "    sizesPyeong: [],\n"
            f"    moveInYear: {int(move_in) if move_in.isdigit() else 2029},\n"
            + (f"    households: {households},\n" if households else "")
            + f"    commuteMinutes: COMMUTE.{reg}, // mock 추정\n"
            f"    metrics: {METRICS}, // placeholder seed(실측 아님)\n"
            '    housingType: "apartment",\n'
            "    subscription: {\n"
            '      type: "general",\n'
            f"      scheduleNote: {esc(note)},\n"
            f'      conditions: {{ ...regulatoryConditions("{area}", {{ overcrowdedZone: true }}), note: "청약홈 공고 기준(일정·규제) · 실거주/거주기간은 공고 확인" }},\n'
            "    },\n"
            "  }"
        )
        entries.append(e)

    header = (
        "// AUTO-GENERATED by scripts/generate-applyhome-presales.py — 편집 금지.\n"
        "// 출처: 한국부동산원 청약홈 APT 분양정보(공공데이터, 2025-11-28). 일정·세대·규제플래그=공식값.\n"
        "// 분양가·평형별은 미포함(주택형별 자료 필요) · metrics/통근은 placeholder. 안양/광명권만.\n"
        'import type { PresaleHome } from "@/domain/types";\n'
        'import { regulatoryConditions } from "@/domain/eligibility";\n\n'
        "const COMMUTE = " + str(COMMUTE).replace("'", '"') + " as const;\n\n"
        "export const APPLYHOME_REAL_PRESALES: PresaleHome[] = [\n"
    )
    open(OUT, "w").write(header + ",\n".join(entries) + "\n];\n")
    print(f"wrote {OUT}: {len(entries)}개 (안양/광명권, {MIN_YEAR}+)")


if __name__ == "__main__":
    main()
